### ISSUE TITLE
Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by liamjones** [clojure/homebrew-tools#3]
From running `brew update` today:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the clojure/tools tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/clojure/homebrew-tools/Formula/clojure.rb:8
```

**Comment by phrohdoh** [comment]
Given https://github.com/clojure/homebrew-tools/commit/9774da58d67b7de2c61e34f103269fbb105538c8 and https://github.com/clojure/homebrew-tools/commit/ae013112ea603e548daae63234feb4c0ba93a693, should this issue be closed (as resolved)?

**Comment by liamjones** [comment]
Yep!
